# There are no required fields for the .travis.yml
# If this file were empty it would still be valid.
#

# A test matrix is possible in Travis by supplying multiple environment
# variables and language versions.
language: php
php:
 - '5.3'

env:
  global:
    - OPENSHIFT_APP_NAME='drupal'
    - OPENSHIFT_REPO_DIR=${TRAVIS_BUILD_DIR}/
    - OPENSHIFT_GIT_DIR=${TRAVIS_BUILD_DIR}.git
    - OPENSHIFT_DATA_DIR=${OPENSHIFT_REPO_DIR}data/
    - OPENSHIFT_MYSQL_DB_USERNAME='root'
    - OPENSHIFT_MYSQL_DB_PASSWORD=''
    - OPENSHIFT_MYSQL_DB_HOST='127.0.0.1'
    - OPENSHIFT_MYSQL_DB_PORT='3306'
    - OPENSHIFT_MYSQL_DB_URL="mysql://$OPENSHIFT_MYSQL_DB_USERNAME@127.0.0.1/"
    - OPENSHIFT_TMP_DIR=/tmp/
    - OPENSHIFT_HOMEDIR=${HOME}
    - DB_ENCODE='utf8'

mysql:
  database: $OPENSHIFT_APP_NAME
  username: $OPENSHIFT_MYSQL_DB_USERNAME
  encoding: $DB_ENCODE


before_install:
  - pear channel-discover pear.drush.org
  

# Prepare to build a test site by installing Drush.
install:
  - pear install drush/drush
  - phpenv rehash
  - mkdir -p "$OPENSHIFT_HOMEDIR/.drush"
  - touch "$OPENSHIFT_HOMEDIR/.drush/drushrc.php"

# Build the test site (there are many ways of accomplishing this step).
before_script:
  - make build
  - make install


# Test the build.
script:
  - make test

# Add deploy step.
deploy:
  provider: openshift
  user: dtkinzer@gmail.com
  password:
    secure: D5guVbZWMFg3lx1GaC6K13iyJFLRqXeCKV9u9VuPQIam/14cGfehG27pBd9VdCpjEMeO/1gZ+tnGhEDnaw3EMZ2n4Jz+kfREf4jWZcSmIY1Q5ccocQL4lTs8HKJ1IEXgi3JUCJhx9f9ynFddDxyzzGKjAJ8tKHto5u64ScLdXZA=
  app: gush
  domain: dkinzer
  on:
    repo: dkinzer/gush
